# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.1
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-{{ checksum "setup.cfg" }}

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip3 install wheel 
            pip3 install pytest pytest-html pytest-cov pytest-pylint pytest-pep8 pprofile

      - run:
          name: build
          command: |
            . venv/bin/activate
            python3 setup.py build

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "setup.cfg" }}

      # disabling tests
      #- run:
      #    name: run tests
      #    command: |
      #      . venv/bin/activate
      #      python3 setup.py test

      - store_artifacts:
          path: test-reports
          destination: test-reports
          
